//! Embed the payload — both DLLs and the word editor — into the installer.
//!
//! The installer must be one file that runs on a machine with no Rust, no
//! PowerShell script beside it and nothing to download, so everything it
//! installs is compiled into it with `include_bytes!`.
//!
//! Inputs are taken from the workspace `target/` directory, or from the
//! `XLIT_DLL_X64` / `XLIT_DLL_X86` / `XLIT_CONFIG_EXE` environment variables if
//! you want to point at artifacts from elsewhere. Anything missing is embedded
//! as `None` and reported by the installer at run time rather than failing the
//! build, because the natural build order is DLLs first, installer last.

use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=XLIT_DLL_X64");
    println!("cargo:rerun-if-env-changed=XLIT_DLL_X86");
    println!("cargo:rerun-if-env-changed=XLIT_CONFIG_EXE");

    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("workspace root")
        .to_path_buf();

    let payload = [
        ("X64", "XLIT_DLL_X64", root.join("target/x86_64-pc-windows-msvc/release/xlit_tsf.dll")),
        ("X86", "XLIT_DLL_X86", root.join("target/i686-pc-windows-msvc/release/xlit_tsf.dll")),
        ("CONFIG", "XLIT_CONFIG_EXE", root.join("target/release/xlit-config.exe")),
    ];

    let mut src = String::from("// Generated by build.rs. Do not edit.\n");
    for (name, var, default) in payload {
        let path = std::env::var_os(var).map(PathBuf::from).unwrap_or(default);
        println!("cargo:rerun-if-changed={}", path.display());
        if path.is_file() {
            src.push_str(&format!(
                "pub static {name}: Option<&[u8]> = Some(include_bytes!(r\"{}\"));\n",
                path.display()
            ));
        } else {
            println!("cargo:warning={name} payload missing: {}", path.display());
            src.push_str(&format!("pub static {name}: Option<&[u8]> = None;\n"));
        }
    }

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR")).join("payload.rs");
    std::fs::write(out, src).expect("write payload.rs");
}
