//! Compile the word list into an `fst::Set` at build time.
//!
//! The set holds one entry per word, `"<latin key>\t<devanagari>"`, so a prefix
//! scan for `"ghar"` finds घर and every longer word whose key starts with it,
//! and a scan for `"ghar\t"` finds just the words that key exactly. Encoding the
//! word into the key is what lets one Latin spelling map to several words —
//! an `fst::Map` value is a single `u64` and could not.
//!
//! Two sources go in. `data/ne-words.tsv` is generated by `tools/mkwords.py`,
//! which derives every key by inverting the Devanagari spelling through the
//! schema. `data/latin-keys-ne.tsv` is hand-written, and holds the words that
//! defeats: an English loanword or a place name with a settled English spelling
//! is reached by typing `computer` or `kathmandu`, not by typing back a
//! transliteration of कम्प्युटर. Same format, same FST, merged here.
//!
//! Building here rather than at startup matters: the Windows text service is
//! loaded into every process that takes keyboard input, and none of them should
//! pay to re-parse 20,000 lines.

use std::io::{BufRead, BufReader, BufWriter};
use std::path::PathBuf;

fn main() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data");
    let sources = [dir.join("ne-words.tsv"), dir.join("latin-keys-ne.tsv")];
    for src in &sources {
        println!("cargo:rerun-if-changed={}", src.display());
    }

    // Collected and sorted here rather than required pre-sorted: the generated
    // file is in order, but the hand-written one is grouped by subject so that
    // it can be read and extended, and sorting 20k short strings costs nothing
    // next to compiling the crate.
    let mut entries: Vec<String> = Vec::new();
    for src in &sources {
        let file = std::fs::File::open(src)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", src.display()));
        for (n, line) in BufReader::new(file).lines().enumerate() {
            let line = line.expect("read line");
            let line = line.trim_end_matches(['\r', '\n']);
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, word)) = line.split_once('\t') else {
                panic!("{}:{}: expected `latin<TAB>devanagari`", src.display(), n + 1);
            };
            let (key, word) = (key.trim(), word.trim());
            if key.is_empty() || word.is_empty() {
                panic!("{}:{}: empty key or word", src.display(), n + 1);
            }
            entries.push(format!("{key}\t{word}"));
        }
    }
    entries.sort_unstable();
    // A word may legitimately be reachable under several keys and a key may
    // legitimately reach several words; what must not happen twice is the same
    // pair, which `SetBuilder` would reject as out of order.
    entries.dedup();

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR")).join("ne-words.fst");
    let mut b = fst::SetBuilder::new(BufWriter::new(
        std::fs::File::create(&out).expect("create fst"),
    ))
    .expect("fst builder");
    for entry in &entries {
        b.insert(entry).expect("insert");
    }
    b.finish().expect("finish fst");
    println!("cargo:warning=ne-words.fst: {} entries", entries.len());
}
