//! Compile the word list into an `fst::Set` at build time.
//!
//! The set holds one entry per word, `"<latin key>\t<devanagari>"`, so a prefix
//! scan for `"ghar"` finds घर and every longer word whose key starts with it,
//! and a scan for `"ghar\t"` finds just the words that key exactly. Encoding the
//! word into the key is what lets one Latin spelling map to several words —
//! an `fst::Map` value is a single `u64` and could not.
//!
//! Two sources go in, and two sets come out — see `src/fold.rs` for the second.
//!
//! Two sources go in. `data/ne-words.tsv` is generated by `tools/mkwords.py`,
//! which derives every key by inverting the Devanagari spelling through the
//! schema. `data/latin-keys-ne.tsv` is hand-written, and holds the words that
//! defeats: an English loanword or a place name with a settled English spelling
//! is reached by typing `computer` or `kathmandu`, not by typing back a
//! transliteration of कम्प्युटर. Same format, same FST, merged here.
//!
//! Building here rather than at startup matters: the Windows text service is
//! loaded into every process that takes keyboard input, and none of them should
//! pay to re-parse 20,000 lines.

use std::io::{BufRead, BufReader, BufWriter};
use std::path::PathBuf;

// Folding must be identical on both sides of the lookup, so the build script
// and the crate compile the same source rather than each keeping a copy.
include!("src/fold.rs");

fn main() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data");
    let sources = [dir.join("ne-words.tsv"), dir.join("latin-keys-ne.tsv")];
    for src in &sources {
        println!("cargo:rerun-if-changed={}", src.display());
    }
    println!("cargo:rerun-if-changed=src/fold.rs");

    // Collected and sorted here rather than required pre-sorted: the generated
    // file is in order, but the hand-written one is grouped by subject so that
    // it can be read and extended, and sorting 20k short strings costs nothing
    // next to compiling the crate.
    let mut entries: Vec<String> = Vec::new();
    for src in &sources {
        let file = std::fs::File::open(src)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", src.display()));
        for (n, line) in BufReader::new(file).lines().enumerate() {
            let line = line.expect("read line");
            let line = line.trim_end_matches(['\r', '\n']);
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, word)) = line.split_once('\t') else {
                panic!("{}:{}: expected `latin<TAB>devanagari`", src.display(), n + 1);
            };
            let (key, word) = (key.trim(), word.trim());
            if key.is_empty() || word.is_empty() {
                panic!("{}:{}: empty key or word", src.display(), n + 1);
            }
            entries.push(format!("{key}\t{word}"));
        }
    }
    // The folded set: the same words under the key a typist would produce.
    // Kept in a second FST rather than mixed into the first so that an exact
    // key match — the user spelled it the way the dictionary does — can still
    // be told apart from, and outrank, a hit that only survived folding.
    let mut folded: Vec<String> = Vec::new();
    for e in &entries {
        let Some((key, word)) = e.split_once('\t') else { continue };
        for variant in key_variants(key) {
            if variant != key {
                folded.push(format!("{variant}\t{word}"));
            }
        }
    }

    entries.sort_unstable();
    // A word may legitimately be reachable under several keys and a key may
    // legitimately reach several words; what must not happen twice is the same
    // pair, which `SetBuilder` would reject as out of order.
    entries.dedup();
    folded.sort_unstable();
    folded.dedup();

    let dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    write_fst(&dir.join("ne-words.fst"), &entries);
    write_fst(&dir.join("ne-folded.fst"), &folded);
    println!(
        "cargo:warning=ne-words.fst: {} entries, ne-folded.fst: {}",
        entries.len(),
        folded.len()
    );
}

fn write_fst(path: &PathBuf, entries: &[String]) {
    let mut b = fst::SetBuilder::new(BufWriter::new(
        std::fs::File::create(path).expect("create fst"),
    ))
    .expect("fst builder");
    for entry in entries {
        b.insert(entry).expect("insert");
    }
    b.finish().expect("finish fst");
}
